package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlWorkbookName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Deliberately invalid workbook-shaped DTO: its {@code @PxlWorkbookName} field is an {@code int} rather
 * than a {@code String}, which pxl rejects while resolving the export metadata.
 *
 * <p>Used to drive a deterministic <em>generation-time</em> failure (as opposed to a failure while writing
 * to the destination), so tests can assert that a response destination is left untouched when generation
 * blows up.</p>
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestBadNameWorkbook {

    @PxlWorkbookName
    private int workbookName;
}
