package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlSheet;
import io.github.hclimkr.pxl.annotation.PxlWorkbookName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Workbook-shaped DTO whose single sheet is named with a Korean syllable, used to pin the NFC normalization
 * the CSV importer applies to a sheet name derived from a file name.
 *
 * <p>The sheet name is spelled as a unicode escape on purpose. Written literally it would carry whichever
 * form the editor happened to save, and the test could then pass without anything having normalized; the
 * escape pins it to U+AC00, the precomposed syllable. The file name the test supplies carries the decomposed
 * pair U+1100 U+1161 instead - the form macOS hands out. The core matches sheet names by equality (whitespace
 * stripped, case folded) and applies no Unicode normalization of its own, so the two only meet if the
 * importer normalized.</p>
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestKoreanSheetWorkbook {

    @PxlWorkbookName
    private String workbookName;

    @PxlSheet(name = "\uAC00")
    private List<TestUser> users;
}
