package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlSheet;
import io.github.hclimkr.pxl.annotation.PxlWorkbook;
import io.github.hclimkr.pxl.annotation.PxlWorkbookName;
import io.github.hclimkr.pxl.type.PxlExcelEngine;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Workbook-shaped DTO that declares its export engine on the class itself, unlike {@link TestWorkbook},
 * which carries no {@code @PxlWorkbook} annotation at all.
 *
 * <p>This is what makes the exporters' "no option → the workbook's own declared engine" fallback observable:
 * with {@code TestWorkbook} that branch and the plain default both yield XLSX, so they cannot be told
 * apart.</p>
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@PxlWorkbook(exportExcelEngine = PxlExcelEngine.HSSF)
public class TestHssfWorkbook {

    @PxlWorkbookName
    private String workbookName;

    @PxlSheet(name = "Users")
    private List<TestUser> users;
}
