package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlSheet;
import io.github.hclimkr.pxl.annotation.PxlWorkbookName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Workbook-shaped DTO with two sheets, {@code Users} and {@code Admins}.
 *
 * <p>Unlike {@link TestWorkbook} this exercises the genuinely multi-sheet paths: several CSV uploads
 * grouped into one workbook object (one file per sheet), and multi-sheet Excel round trips.</p>
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestMultiSheetWorkbook {

    @PxlWorkbookName
    private String workbookName;

    @PxlSheet(name = "Users")
    private List<TestUser> users;

    @PxlSheet(name = "Admins")
    private List<TestUser> admins;
}
