package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlSheet;
import io.github.hclimkr.pxl.annotation.PxlWorkbookName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Simple workbook-shaped DTO with a name field and a single {@code Users} sheet, used by the
 * pxl-spring tests for workbook-object export/import round trips.
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestWorkbook {

    @PxlWorkbookName
    private String workbookName;

    @PxlSheet(name = "Users")
    private List<TestUser> users;
}
