package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlColumn;
import io.github.hclimkr.pxl.styler.header.PxlHeaderOptionalStyler;
import io.github.hclimkr.pxl.styler.header.PxlHeaderRequiredStyler;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;

/**
 * Row DTO exercising the pxl {@code mandatory}&rarr;{@code required} rename. The {@code name} column is
 * required (bean-validation {@code @NotBlank}) and explicitly wires the renamed
 * {@code @PxlColumn(exportColumnRequiredHeaderCellStyler = ...)} property - formerly
 * {@code exportColumnMandatoryTitleCellStyler} - while {@code age} stays optional and wires
 * {@code exportColumnOptionalHeaderCellStyler}. On export the required header renders with the required
 * styler (black font) and the optional header with the optional styler (grey font). Referencing the new
 * property name here makes the test module fail to compile against a pxl version still using the old name.
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestRequiredUser {

    @NotBlank
    @PxlColumn(name = "Name", exportSample = "Alice",
            exportColumnRequiredHeaderCellStyler = PxlHeaderRequiredStyler.class)
    private String name;

    @PxlColumn(name = "Age", exportSample = "30",
            exportColumnOptionalHeaderCellStyler = PxlHeaderOptionalStyler.class)
    private int age;
}
