package io.github.hclimkr.pxl.spring.tcdata;

import io.github.hclimkr.pxl.annotation.PxlColumn;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Simple row DTO used by the pxl-spring tests. Columns map to {@code Name} / {@code Age} headers.
 *
 * <p>Boilerplate (getters/setters, no-arg and all-args constructors) is generated by Lombok; pxl binds
 * via the field annotations and the Lombok-generated no-arg constructor.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestUser {

    @PxlColumn(name = "Name", exportSample = "Alice")
    private String name;

    @PxlColumn(name = "Age", exportSample = "30")
    private int age;
}
